// Code generated by ent, DO NOT EDIT.

package codexregistrationcandidate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the codexregistrationcandidate type in the database.
	Label = "codex_registration_candidate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSourcePath holds the string denoting the source_path field in the database.
	FieldSourcePath = "source_path"
	// FieldSourceFilename holds the string denoting the source_filename field in the database.
	FieldSourceFilename = "source_filename"
	// FieldSourceMtime holds the string denoting the source_mtime field in the database.
	FieldSourceMtime = "source_mtime"
	// FieldSourceFingerprint holds the string denoting the source_fingerprint field in the database.
	FieldSourceFingerprint = "source_fingerprint"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastRefreshAt holds the string denoting the last_refresh_at field in the database.
	FieldLastRefreshAt = "last_refresh_at"
	// FieldLivenessStatus holds the string denoting the liveness_status field in the database.
	FieldLivenessStatus = "liveness_status"
	// FieldWorkflowState holds the string denoting the workflow_state field in the database.
	FieldWorkflowState = "workflow_state"
	// FieldStatusReason holds the string denoting the status_reason field in the database.
	FieldStatusReason = "status_reason"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldImportedAccountID holds the string denoting the imported_account_id field in the database.
	FieldImportedAccountID = "imported_account_id"
	// FieldImportedAt holds the string denoting the imported_at field in the database.
	FieldImportedAt = "imported_at"
	// Table holds the table name of the codexregistrationcandidate in the database.
	Table = "codex_registration_candidates"
)

// Columns holds all SQL columns for codexregistrationcandidate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSourcePath,
	FieldSourceFilename,
	FieldSourceMtime,
	FieldSourceFingerprint,
	FieldEmail,
	FieldAccountID,
	FieldType,
	FieldExpiresAt,
	FieldLastRefreshAt,
	FieldLivenessStatus,
	FieldWorkflowState,
	FieldStatusReason,
	FieldLastCheckedAt,
	FieldImportedAccountID,
	FieldImportedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SourcePathValidator is a validator for the "source_path" field. It is called by the builders before save.
	SourcePathValidator func(string) error
	// SourceFilenameValidator is a validator for the "source_filename" field. It is called by the builders before save.
	SourceFilenameValidator func(string) error
	// SourceFingerprintValidator is a validator for the "source_fingerprint" field. It is called by the builders before save.
	SourceFingerprintValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	AccountIDValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultLivenessStatus holds the default value on creation for the "liveness_status" field.
	DefaultLivenessStatus string
	// LivenessStatusValidator is a validator for the "liveness_status" field. It is called by the builders before save.
	LivenessStatusValidator func(string) error
	// DefaultWorkflowState holds the default value on creation for the "workflow_state" field.
	DefaultWorkflowState string
	// WorkflowStateValidator is a validator for the "workflow_state" field. It is called by the builders before save.
	WorkflowStateValidator func(string) error
)

// OrderOption defines the ordering options for the CodexRegistrationCandidate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySourcePath orders the results by the source_path field.
func BySourcePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePath, opts...).ToFunc()
}

// BySourceFilename orders the results by the source_filename field.
func BySourceFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceFilename, opts...).ToFunc()
}

// BySourceMtime orders the results by the source_mtime field.
func BySourceMtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceMtime, opts...).ToFunc()
}

// BySourceFingerprint orders the results by the source_fingerprint field.
func BySourceFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceFingerprint, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastRefreshAt orders the results by the last_refresh_at field.
func ByLastRefreshAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshAt, opts...).ToFunc()
}

// ByLivenessStatus orders the results by the liveness_status field.
func ByLivenessStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLivenessStatus, opts...).ToFunc()
}

// ByWorkflowState orders the results by the workflow_state field.
func ByWorkflowState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowState, opts...).ToFunc()
}

// ByStatusReason orders the results by the status_reason field.
func ByStatusReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusReason, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByImportedAccountID orders the results by the imported_account_id field.
func ByImportedAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportedAccountID, opts...).ToFunc()
}

// ByImportedAt orders the results by the imported_at field.
func ByImportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportedAt, opts...).ToFunc()
}
