// Code generated by ent, DO NOT EDIT.

package codexregistrationcandidate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourcePath applies equality check predicate on the "source_path" field. It's identical to SourcePathEQ.
func SourcePath(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourcePath, v))
}

// SourceFilename applies equality check predicate on the "source_filename" field. It's identical to SourceFilenameEQ.
func SourceFilename(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourceFilename, v))
}

// SourceMtime applies equality check predicate on the "source_mtime" field. It's identical to SourceMtimeEQ.
func SourceMtime(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourceMtime, v))
}

// SourceFingerprint applies equality check predicate on the "source_fingerprint" field. It's identical to SourceFingerprintEQ.
func SourceFingerprint(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourceFingerprint, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldEmail, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldAccountID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldType, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldExpiresAt, v))
}

// LastRefreshAt applies equality check predicate on the "last_refresh_at" field. It's identical to LastRefreshAtEQ.
func LastRefreshAt(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldLastRefreshAt, v))
}

// LivenessStatus applies equality check predicate on the "liveness_status" field. It's identical to LivenessStatusEQ.
func LivenessStatus(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldLivenessStatus, v))
}

// WorkflowState applies equality check predicate on the "workflow_state" field. It's identical to WorkflowStateEQ.
func WorkflowState(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldWorkflowState, v))
}

// StatusReason applies equality check predicate on the "status_reason" field. It's identical to StatusReasonEQ.
func StatusReason(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldStatusReason, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldLastCheckedAt, v))
}

// ImportedAccountID applies equality check predicate on the "imported_account_id" field. It's identical to ImportedAccountIDEQ.
func ImportedAccountID(v int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldImportedAccountID, v))
}

// ImportedAt applies equality check predicate on the "imported_at" field. It's identical to ImportedAtEQ.
func ImportedAt(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldImportedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldUpdatedAt, v))
}

// SourcePathEQ applies the EQ predicate on the "source_path" field.
func SourcePathEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourcePath, v))
}

// SourcePathNEQ applies the NEQ predicate on the "source_path" field.
func SourcePathNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldSourcePath, v))
}

// SourcePathIn applies the In predicate on the "source_path" field.
func SourcePathIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldSourcePath, vs...))
}

// SourcePathNotIn applies the NotIn predicate on the "source_path" field.
func SourcePathNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldSourcePath, vs...))
}

// SourcePathGT applies the GT predicate on the "source_path" field.
func SourcePathGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldSourcePath, v))
}

// SourcePathGTE applies the GTE predicate on the "source_path" field.
func SourcePathGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldSourcePath, v))
}

// SourcePathLT applies the LT predicate on the "source_path" field.
func SourcePathLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldSourcePath, v))
}

// SourcePathLTE applies the LTE predicate on the "source_path" field.
func SourcePathLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldSourcePath, v))
}

// SourcePathContains applies the Contains predicate on the "source_path" field.
func SourcePathContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldSourcePath, v))
}

// SourcePathHasPrefix applies the HasPrefix predicate on the "source_path" field.
func SourcePathHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldSourcePath, v))
}

// SourcePathHasSuffix applies the HasSuffix predicate on the "source_path" field.
func SourcePathHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldSourcePath, v))
}

// SourcePathEqualFold applies the EqualFold predicate on the "source_path" field.
func SourcePathEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldSourcePath, v))
}

// SourcePathContainsFold applies the ContainsFold predicate on the "source_path" field.
func SourcePathContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldSourcePath, v))
}

// SourceFilenameEQ applies the EQ predicate on the "source_filename" field.
func SourceFilenameEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourceFilename, v))
}

// SourceFilenameNEQ applies the NEQ predicate on the "source_filename" field.
func SourceFilenameNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldSourceFilename, v))
}

// SourceFilenameIn applies the In predicate on the "source_filename" field.
func SourceFilenameIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldSourceFilename, vs...))
}

// SourceFilenameNotIn applies the NotIn predicate on the "source_filename" field.
func SourceFilenameNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldSourceFilename, vs...))
}

// SourceFilenameGT applies the GT predicate on the "source_filename" field.
func SourceFilenameGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldSourceFilename, v))
}

// SourceFilenameGTE applies the GTE predicate on the "source_filename" field.
func SourceFilenameGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldSourceFilename, v))
}

// SourceFilenameLT applies the LT predicate on the "source_filename" field.
func SourceFilenameLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldSourceFilename, v))
}

// SourceFilenameLTE applies the LTE predicate on the "source_filename" field.
func SourceFilenameLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldSourceFilename, v))
}

// SourceFilenameContains applies the Contains predicate on the "source_filename" field.
func SourceFilenameContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldSourceFilename, v))
}

// SourceFilenameHasPrefix applies the HasPrefix predicate on the "source_filename" field.
func SourceFilenameHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldSourceFilename, v))
}

// SourceFilenameHasSuffix applies the HasSuffix predicate on the "source_filename" field.
func SourceFilenameHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldSourceFilename, v))
}

// SourceFilenameEqualFold applies the EqualFold predicate on the "source_filename" field.
func SourceFilenameEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldSourceFilename, v))
}

// SourceFilenameContainsFold applies the ContainsFold predicate on the "source_filename" field.
func SourceFilenameContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldSourceFilename, v))
}

// SourceMtimeEQ applies the EQ predicate on the "source_mtime" field.
func SourceMtimeEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourceMtime, v))
}

// SourceMtimeNEQ applies the NEQ predicate on the "source_mtime" field.
func SourceMtimeNEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldSourceMtime, v))
}

// SourceMtimeIn applies the In predicate on the "source_mtime" field.
func SourceMtimeIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldSourceMtime, vs...))
}

// SourceMtimeNotIn applies the NotIn predicate on the "source_mtime" field.
func SourceMtimeNotIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldSourceMtime, vs...))
}

// SourceMtimeGT applies the GT predicate on the "source_mtime" field.
func SourceMtimeGT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldSourceMtime, v))
}

// SourceMtimeGTE applies the GTE predicate on the "source_mtime" field.
func SourceMtimeGTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldSourceMtime, v))
}

// SourceMtimeLT applies the LT predicate on the "source_mtime" field.
func SourceMtimeLT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldSourceMtime, v))
}

// SourceMtimeLTE applies the LTE predicate on the "source_mtime" field.
func SourceMtimeLTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldSourceMtime, v))
}

// SourceFingerprintEQ applies the EQ predicate on the "source_fingerprint" field.
func SourceFingerprintEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldSourceFingerprint, v))
}

// SourceFingerprintNEQ applies the NEQ predicate on the "source_fingerprint" field.
func SourceFingerprintNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldSourceFingerprint, v))
}

// SourceFingerprintIn applies the In predicate on the "source_fingerprint" field.
func SourceFingerprintIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldSourceFingerprint, vs...))
}

// SourceFingerprintNotIn applies the NotIn predicate on the "source_fingerprint" field.
func SourceFingerprintNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldSourceFingerprint, vs...))
}

// SourceFingerprintGT applies the GT predicate on the "source_fingerprint" field.
func SourceFingerprintGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldSourceFingerprint, v))
}

// SourceFingerprintGTE applies the GTE predicate on the "source_fingerprint" field.
func SourceFingerprintGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldSourceFingerprint, v))
}

// SourceFingerprintLT applies the LT predicate on the "source_fingerprint" field.
func SourceFingerprintLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldSourceFingerprint, v))
}

// SourceFingerprintLTE applies the LTE predicate on the "source_fingerprint" field.
func SourceFingerprintLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldSourceFingerprint, v))
}

// SourceFingerprintContains applies the Contains predicate on the "source_fingerprint" field.
func SourceFingerprintContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldSourceFingerprint, v))
}

// SourceFingerprintHasPrefix applies the HasPrefix predicate on the "source_fingerprint" field.
func SourceFingerprintHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldSourceFingerprint, v))
}

// SourceFingerprintHasSuffix applies the HasSuffix predicate on the "source_fingerprint" field.
func SourceFingerprintHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldSourceFingerprint, v))
}

// SourceFingerprintEqualFold applies the EqualFold predicate on the "source_fingerprint" field.
func SourceFingerprintEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldSourceFingerprint, v))
}

// SourceFingerprintContainsFold applies the ContainsFold predicate on the "source_fingerprint" field.
func SourceFingerprintContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldSourceFingerprint, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldEmail, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldAccountID))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldAccountID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldType, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldExpiresAt))
}

// LastRefreshAtEQ applies the EQ predicate on the "last_refresh_at" field.
func LastRefreshAtEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtNEQ applies the NEQ predicate on the "last_refresh_at" field.
func LastRefreshAtNEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtIn applies the In predicate on the "last_refresh_at" field.
func LastRefreshAtIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtNotIn applies the NotIn predicate on the "last_refresh_at" field.
func LastRefreshAtNotIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtGT applies the GT predicate on the "last_refresh_at" field.
func LastRefreshAtGT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldLastRefreshAt, v))
}

// LastRefreshAtGTE applies the GTE predicate on the "last_refresh_at" field.
func LastRefreshAtGTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldLastRefreshAt, v))
}

// LastRefreshAtLT applies the LT predicate on the "last_refresh_at" field.
func LastRefreshAtLT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldLastRefreshAt, v))
}

// LastRefreshAtLTE applies the LTE predicate on the "last_refresh_at" field.
func LastRefreshAtLTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldLastRefreshAt, v))
}

// LastRefreshAtIsNil applies the IsNil predicate on the "last_refresh_at" field.
func LastRefreshAtIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldLastRefreshAt))
}

// LastRefreshAtNotNil applies the NotNil predicate on the "last_refresh_at" field.
func LastRefreshAtNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldLastRefreshAt))
}

// LivenessStatusEQ applies the EQ predicate on the "liveness_status" field.
func LivenessStatusEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldLivenessStatus, v))
}

// LivenessStatusNEQ applies the NEQ predicate on the "liveness_status" field.
func LivenessStatusNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldLivenessStatus, v))
}

// LivenessStatusIn applies the In predicate on the "liveness_status" field.
func LivenessStatusIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldLivenessStatus, vs...))
}

// LivenessStatusNotIn applies the NotIn predicate on the "liveness_status" field.
func LivenessStatusNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldLivenessStatus, vs...))
}

// LivenessStatusGT applies the GT predicate on the "liveness_status" field.
func LivenessStatusGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldLivenessStatus, v))
}

// LivenessStatusGTE applies the GTE predicate on the "liveness_status" field.
func LivenessStatusGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldLivenessStatus, v))
}

// LivenessStatusLT applies the LT predicate on the "liveness_status" field.
func LivenessStatusLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldLivenessStatus, v))
}

// LivenessStatusLTE applies the LTE predicate on the "liveness_status" field.
func LivenessStatusLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldLivenessStatus, v))
}

// LivenessStatusContains applies the Contains predicate on the "liveness_status" field.
func LivenessStatusContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldLivenessStatus, v))
}

// LivenessStatusHasPrefix applies the HasPrefix predicate on the "liveness_status" field.
func LivenessStatusHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldLivenessStatus, v))
}

// LivenessStatusHasSuffix applies the HasSuffix predicate on the "liveness_status" field.
func LivenessStatusHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldLivenessStatus, v))
}

// LivenessStatusEqualFold applies the EqualFold predicate on the "liveness_status" field.
func LivenessStatusEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldLivenessStatus, v))
}

// LivenessStatusContainsFold applies the ContainsFold predicate on the "liveness_status" field.
func LivenessStatusContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldLivenessStatus, v))
}

// WorkflowStateEQ applies the EQ predicate on the "workflow_state" field.
func WorkflowStateEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldWorkflowState, v))
}

// WorkflowStateNEQ applies the NEQ predicate on the "workflow_state" field.
func WorkflowStateNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldWorkflowState, v))
}

// WorkflowStateIn applies the In predicate on the "workflow_state" field.
func WorkflowStateIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldWorkflowState, vs...))
}

// WorkflowStateNotIn applies the NotIn predicate on the "workflow_state" field.
func WorkflowStateNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldWorkflowState, vs...))
}

// WorkflowStateGT applies the GT predicate on the "workflow_state" field.
func WorkflowStateGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldWorkflowState, v))
}

// WorkflowStateGTE applies the GTE predicate on the "workflow_state" field.
func WorkflowStateGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldWorkflowState, v))
}

// WorkflowStateLT applies the LT predicate on the "workflow_state" field.
func WorkflowStateLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldWorkflowState, v))
}

// WorkflowStateLTE applies the LTE predicate on the "workflow_state" field.
func WorkflowStateLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldWorkflowState, v))
}

// WorkflowStateContains applies the Contains predicate on the "workflow_state" field.
func WorkflowStateContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldWorkflowState, v))
}

// WorkflowStateHasPrefix applies the HasPrefix predicate on the "workflow_state" field.
func WorkflowStateHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldWorkflowState, v))
}

// WorkflowStateHasSuffix applies the HasSuffix predicate on the "workflow_state" field.
func WorkflowStateHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldWorkflowState, v))
}

// WorkflowStateEqualFold applies the EqualFold predicate on the "workflow_state" field.
func WorkflowStateEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldWorkflowState, v))
}

// WorkflowStateContainsFold applies the ContainsFold predicate on the "workflow_state" field.
func WorkflowStateContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldWorkflowState, v))
}

// StatusReasonEQ applies the EQ predicate on the "status_reason" field.
func StatusReasonEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldStatusReason, v))
}

// StatusReasonNEQ applies the NEQ predicate on the "status_reason" field.
func StatusReasonNEQ(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldStatusReason, v))
}

// StatusReasonIn applies the In predicate on the "status_reason" field.
func StatusReasonIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldStatusReason, vs...))
}

// StatusReasonNotIn applies the NotIn predicate on the "status_reason" field.
func StatusReasonNotIn(vs ...string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldStatusReason, vs...))
}

// StatusReasonGT applies the GT predicate on the "status_reason" field.
func StatusReasonGT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldStatusReason, v))
}

// StatusReasonGTE applies the GTE predicate on the "status_reason" field.
func StatusReasonGTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldStatusReason, v))
}

// StatusReasonLT applies the LT predicate on the "status_reason" field.
func StatusReasonLT(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldStatusReason, v))
}

// StatusReasonLTE applies the LTE predicate on the "status_reason" field.
func StatusReasonLTE(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldStatusReason, v))
}

// StatusReasonContains applies the Contains predicate on the "status_reason" field.
func StatusReasonContains(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContains(FieldStatusReason, v))
}

// StatusReasonHasPrefix applies the HasPrefix predicate on the "status_reason" field.
func StatusReasonHasPrefix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasPrefix(FieldStatusReason, v))
}

// StatusReasonHasSuffix applies the HasSuffix predicate on the "status_reason" field.
func StatusReasonHasSuffix(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldHasSuffix(FieldStatusReason, v))
}

// StatusReasonIsNil applies the IsNil predicate on the "status_reason" field.
func StatusReasonIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldStatusReason))
}

// StatusReasonNotNil applies the NotNil predicate on the "status_reason" field.
func StatusReasonNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldStatusReason))
}

// StatusReasonEqualFold applies the EqualFold predicate on the "status_reason" field.
func StatusReasonEqualFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEqualFold(FieldStatusReason, v))
}

// StatusReasonContainsFold applies the ContainsFold predicate on the "status_reason" field.
func StatusReasonContainsFold(v string) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldContainsFold(FieldStatusReason, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldLastCheckedAt))
}

// ImportedAccountIDEQ applies the EQ predicate on the "imported_account_id" field.
func ImportedAccountIDEQ(v int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldImportedAccountID, v))
}

// ImportedAccountIDNEQ applies the NEQ predicate on the "imported_account_id" field.
func ImportedAccountIDNEQ(v int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldImportedAccountID, v))
}

// ImportedAccountIDIn applies the In predicate on the "imported_account_id" field.
func ImportedAccountIDIn(vs ...int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldImportedAccountID, vs...))
}

// ImportedAccountIDNotIn applies the NotIn predicate on the "imported_account_id" field.
func ImportedAccountIDNotIn(vs ...int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldImportedAccountID, vs...))
}

// ImportedAccountIDGT applies the GT predicate on the "imported_account_id" field.
func ImportedAccountIDGT(v int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldImportedAccountID, v))
}

// ImportedAccountIDGTE applies the GTE predicate on the "imported_account_id" field.
func ImportedAccountIDGTE(v int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldImportedAccountID, v))
}

// ImportedAccountIDLT applies the LT predicate on the "imported_account_id" field.
func ImportedAccountIDLT(v int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldImportedAccountID, v))
}

// ImportedAccountIDLTE applies the LTE predicate on the "imported_account_id" field.
func ImportedAccountIDLTE(v int64) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldImportedAccountID, v))
}

// ImportedAccountIDIsNil applies the IsNil predicate on the "imported_account_id" field.
func ImportedAccountIDIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldImportedAccountID))
}

// ImportedAccountIDNotNil applies the NotNil predicate on the "imported_account_id" field.
func ImportedAccountIDNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldImportedAccountID))
}

// ImportedAtEQ applies the EQ predicate on the "imported_at" field.
func ImportedAtEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldEQ(FieldImportedAt, v))
}

// ImportedAtNEQ applies the NEQ predicate on the "imported_at" field.
func ImportedAtNEQ(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNEQ(FieldImportedAt, v))
}

// ImportedAtIn applies the In predicate on the "imported_at" field.
func ImportedAtIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIn(FieldImportedAt, vs...))
}

// ImportedAtNotIn applies the NotIn predicate on the "imported_at" field.
func ImportedAtNotIn(vs ...time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotIn(FieldImportedAt, vs...))
}

// ImportedAtGT applies the GT predicate on the "imported_at" field.
func ImportedAtGT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGT(FieldImportedAt, v))
}

// ImportedAtGTE applies the GTE predicate on the "imported_at" field.
func ImportedAtGTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldGTE(FieldImportedAt, v))
}

// ImportedAtLT applies the LT predicate on the "imported_at" field.
func ImportedAtLT(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLT(FieldImportedAt, v))
}

// ImportedAtLTE applies the LTE predicate on the "imported_at" field.
func ImportedAtLTE(v time.Time) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldLTE(FieldImportedAt, v))
}

// ImportedAtIsNil applies the IsNil predicate on the "imported_at" field.
func ImportedAtIsNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldIsNull(FieldImportedAt))
}

// ImportedAtNotNil applies the NotNil predicate on the "imported_at" field.
func ImportedAtNotNil() predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.FieldNotNull(FieldImportedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexRegistrationCandidate) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexRegistrationCandidate) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexRegistrationCandidate) predicate.CodexRegistrationCandidate {
	return predicate.CodexRegistrationCandidate(sql.NotPredicates(p))
}
