// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/codexregistrationcandidate"
)

// CodexRegistrationCandidate is the model entity for the CodexRegistrationCandidate schema.
type CodexRegistrationCandidate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SourcePath holds the value of the "source_path" field.
	SourcePath string `json:"source_path,omitempty"`
	// SourceFilename holds the value of the "source_filename" field.
	SourceFilename string `json:"source_filename,omitempty"`
	// SourceMtime holds the value of the "source_mtime" field.
	SourceMtime time.Time `json:"source_mtime,omitempty"`
	// SourceFingerprint holds the value of the "source_fingerprint" field.
	SourceFingerprint string `json:"source_fingerprint,omitempty"`
	// Email holds the value of the "email" field.
	Email *string `json:"email,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *string `json:"account_id,omitempty"`
	// Type holds the value of the "type" field.
	Type *string `json:"type,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// LastRefreshAt holds the value of the "last_refresh_at" field.
	LastRefreshAt *time.Time `json:"last_refresh_at,omitempty"`
	// LivenessStatus holds the value of the "liveness_status" field.
	LivenessStatus string `json:"liveness_status,omitempty"`
	// WorkflowState holds the value of the "workflow_state" field.
	WorkflowState string `json:"workflow_state,omitempty"`
	// StatusReason holds the value of the "status_reason" field.
	StatusReason *string `json:"status_reason,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// ImportedAccountID holds the value of the "imported_account_id" field.
	ImportedAccountID *int64 `json:"imported_account_id,omitempty"`
	// ImportedAt holds the value of the "imported_at" field.
	ImportedAt   *time.Time `json:"imported_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexRegistrationCandidate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexregistrationcandidate.FieldID, codexregistrationcandidate.FieldImportedAccountID:
			values[i] = new(sql.NullInt64)
		case codexregistrationcandidate.FieldSourcePath, codexregistrationcandidate.FieldSourceFilename, codexregistrationcandidate.FieldSourceFingerprint, codexregistrationcandidate.FieldEmail, codexregistrationcandidate.FieldAccountID, codexregistrationcandidate.FieldType, codexregistrationcandidate.FieldLivenessStatus, codexregistrationcandidate.FieldWorkflowState, codexregistrationcandidate.FieldStatusReason:
			values[i] = new(sql.NullString)
		case codexregistrationcandidate.FieldCreatedAt, codexregistrationcandidate.FieldUpdatedAt, codexregistrationcandidate.FieldSourceMtime, codexregistrationcandidate.FieldExpiresAt, codexregistrationcandidate.FieldLastRefreshAt, codexregistrationcandidate.FieldLastCheckedAt, codexregistrationcandidate.FieldImportedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexRegistrationCandidate fields.
func (_m *CodexRegistrationCandidate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexregistrationcandidate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case codexregistrationcandidate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case codexregistrationcandidate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case codexregistrationcandidate.FieldSourcePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_path", values[i])
			} else if value.Valid {
				_m.SourcePath = value.String
			}
		case codexregistrationcandidate.FieldSourceFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_filename", values[i])
			} else if value.Valid {
				_m.SourceFilename = value.String
			}
		case codexregistrationcandidate.FieldSourceMtime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field source_mtime", values[i])
			} else if value.Valid {
				_m.SourceMtime = value.Time
			}
		case codexregistrationcandidate.FieldSourceFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_fingerprint", values[i])
			} else if value.Valid {
				_m.SourceFingerprint = value.String
			}
		case codexregistrationcandidate.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = new(string)
				*_m.Email = value.String
			}
		case codexregistrationcandidate.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(string)
				*_m.AccountID = value.String
			}
		case codexregistrationcandidate.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = new(string)
				*_m.Type = value.String
			}
		case codexregistrationcandidate.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case codexregistrationcandidate.FieldLastRefreshAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_refresh_at", values[i])
			} else if value.Valid {
				_m.LastRefreshAt = new(time.Time)
				*_m.LastRefreshAt = value.Time
			}
		case codexregistrationcandidate.FieldLivenessStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field liveness_status", values[i])
			} else if value.Valid {
				_m.LivenessStatus = value.String
			}
		case codexregistrationcandidate.FieldWorkflowState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_state", values[i])
			} else if value.Valid {
				_m.WorkflowState = value.String
			}
		case codexregistrationcandidate.FieldStatusReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status_reason", values[i])
			} else if value.Valid {
				_m.StatusReason = new(string)
				*_m.StatusReason = value.String
			}
		case codexregistrationcandidate.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case codexregistrationcandidate.FieldImportedAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field imported_account_id", values[i])
			} else if value.Valid {
				_m.ImportedAccountID = new(int64)
				*_m.ImportedAccountID = value.Int64
			}
		case codexregistrationcandidate.FieldImportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field imported_at", values[i])
			} else if value.Valid {
				_m.ImportedAt = new(time.Time)
				*_m.ImportedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexRegistrationCandidate.
// This includes values selected through modifiers, order, etc.
func (_m *CodexRegistrationCandidate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CodexRegistrationCandidate.
// Note that you need to call CodexRegistrationCandidate.Unwrap() before calling this method if this CodexRegistrationCandidate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexRegistrationCandidate) Update() *CodexRegistrationCandidateUpdateOne {
	return NewCodexRegistrationCandidateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexRegistrationCandidate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexRegistrationCandidate) Unwrap() *CodexRegistrationCandidate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexRegistrationCandidate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexRegistrationCandidate) String() string {
	var builder strings.Builder
	builder.WriteString("CodexRegistrationCandidate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source_path=")
	builder.WriteString(_m.SourcePath)
	builder.WriteString(", ")
	builder.WriteString("source_filename=")
	builder.WriteString(_m.SourceFilename)
	builder.WriteString(", ")
	builder.WriteString("source_mtime=")
	builder.WriteString(_m.SourceMtime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source_fingerprint=")
	builder.WriteString(_m.SourceFingerprint)
	builder.WriteString(", ")
	if v := _m.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Type; v != nil {
		builder.WriteString("type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastRefreshAt; v != nil {
		builder.WriteString("last_refresh_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("liveness_status=")
	builder.WriteString(_m.LivenessStatus)
	builder.WriteString(", ")
	builder.WriteString("workflow_state=")
	builder.WriteString(_m.WorkflowState)
	builder.WriteString(", ")
	if v := _m.StatusReason; v != nil {
		builder.WriteString("status_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ImportedAccountID; v != nil {
		builder.WriteString("imported_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImportedAt; v != nil {
		builder.WriteString("imported_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CodexRegistrationCandidates is a parsable slice of CodexRegistrationCandidate.
type CodexRegistrationCandidates []*CodexRegistrationCandidate
