// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexregistrationcandidate"
)

// CodexRegistrationCandidateCreate is the builder for creating a CodexRegistrationCandidate entity.
type CodexRegistrationCandidateCreate struct {
	config
	mutation *CodexRegistrationCandidateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexRegistrationCandidateCreate) SetCreatedAt(v time.Time) *CodexRegistrationCandidateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableCreatedAt(v *time.Time) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CodexRegistrationCandidateCreate) SetUpdatedAt(v time.Time) *CodexRegistrationCandidateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableUpdatedAt(v *time.Time) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSourcePath sets the "source_path" field.
func (_c *CodexRegistrationCandidateCreate) SetSourcePath(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetSourcePath(v)
	return _c
}

// SetSourceFilename sets the "source_filename" field.
func (_c *CodexRegistrationCandidateCreate) SetSourceFilename(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetSourceFilename(v)
	return _c
}

// SetSourceMtime sets the "source_mtime" field.
func (_c *CodexRegistrationCandidateCreate) SetSourceMtime(v time.Time) *CodexRegistrationCandidateCreate {
	_c.mutation.SetSourceMtime(v)
	return _c
}

// SetSourceFingerprint sets the "source_fingerprint" field.
func (_c *CodexRegistrationCandidateCreate) SetSourceFingerprint(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetSourceFingerprint(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *CodexRegistrationCandidateCreate) SetEmail(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableEmail(v *string) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *CodexRegistrationCandidateCreate) SetAccountID(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableAccountID(v *string) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *CodexRegistrationCandidateCreate) SetType(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableType(v *string) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CodexRegistrationCandidateCreate) SetExpiresAt(v time.Time) *CodexRegistrationCandidateCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableExpiresAt(v *time.Time) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_c *CodexRegistrationCandidateCreate) SetLastRefreshAt(v time.Time) *CodexRegistrationCandidateCreate {
	_c.mutation.SetLastRefreshAt(v)
	return _c
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableLastRefreshAt(v *time.Time) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetLastRefreshAt(*v)
	}
	return _c
}

// SetLivenessStatus sets the "liveness_status" field.
func (_c *CodexRegistrationCandidateCreate) SetLivenessStatus(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetLivenessStatus(v)
	return _c
}

// SetNillableLivenessStatus sets the "liveness_status" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableLivenessStatus(v *string) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetLivenessStatus(*v)
	}
	return _c
}

// SetWorkflowState sets the "workflow_state" field.
func (_c *CodexRegistrationCandidateCreate) SetWorkflowState(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetWorkflowState(v)
	return _c
}

// SetNillableWorkflowState sets the "workflow_state" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableWorkflowState(v *string) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetWorkflowState(*v)
	}
	return _c
}

// SetStatusReason sets the "status_reason" field.
func (_c *CodexRegistrationCandidateCreate) SetStatusReason(v string) *CodexRegistrationCandidateCreate {
	_c.mutation.SetStatusReason(v)
	return _c
}

// SetNillableStatusReason sets the "status_reason" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableStatusReason(v *string) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetStatusReason(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *CodexRegistrationCandidateCreate) SetLastCheckedAt(v time.Time) *CodexRegistrationCandidateCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableLastCheckedAt(v *time.Time) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetImportedAccountID sets the "imported_account_id" field.
func (_c *CodexRegistrationCandidateCreate) SetImportedAccountID(v int64) *CodexRegistrationCandidateCreate {
	_c.mutation.SetImportedAccountID(v)
	return _c
}

// SetNillableImportedAccountID sets the "imported_account_id" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableImportedAccountID(v *int64) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetImportedAccountID(*v)
	}
	return _c
}

// SetImportedAt sets the "imported_at" field.
func (_c *CodexRegistrationCandidateCreate) SetImportedAt(v time.Time) *CodexRegistrationCandidateCreate {
	_c.mutation.SetImportedAt(v)
	return _c
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_c *CodexRegistrationCandidateCreate) SetNillableImportedAt(v *time.Time) *CodexRegistrationCandidateCreate {
	if v != nil {
		_c.SetImportedAt(*v)
	}
	return _c
}

// Mutation returns the CodexRegistrationCandidateMutation object of the builder.
func (_c *CodexRegistrationCandidateCreate) Mutation() *CodexRegistrationCandidateMutation {
	return _c.mutation
}

// Save creates the CodexRegistrationCandidate in the database.
func (_c *CodexRegistrationCandidateCreate) Save(ctx context.Context) (*CodexRegistrationCandidate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexRegistrationCandidateCreate) SaveX(ctx context.Context) *CodexRegistrationCandidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexRegistrationCandidateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexRegistrationCandidateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexRegistrationCandidateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexregistrationcandidate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := codexregistrationcandidate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LivenessStatus(); !ok {
		v := codexregistrationcandidate.DefaultLivenessStatus
		_c.mutation.SetLivenessStatus(v)
	}
	if _, ok := _c.mutation.WorkflowState(); !ok {
		v := codexregistrationcandidate.DefaultWorkflowState
		_c.mutation.SetWorkflowState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexRegistrationCandidateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.updated_at"`)}
	}
	if _, ok := _c.mutation.SourcePath(); !ok {
		return &ValidationError{Name: "source_path", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.source_path"`)}
	}
	if v, ok := _c.mutation.SourcePath(); ok {
		if err := codexregistrationcandidate.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceFilename(); !ok {
		return &ValidationError{Name: "source_filename", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.source_filename"`)}
	}
	if v, ok := _c.mutation.SourceFilename(); ok {
		if err := codexregistrationcandidate.SourceFilenameValidator(v); err != nil {
			return &ValidationError{Name: "source_filename", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceMtime(); !ok {
		return &ValidationError{Name: "source_mtime", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.source_mtime"`)}
	}
	if _, ok := _c.mutation.SourceFingerprint(); !ok {
		return &ValidationError{Name: "source_fingerprint", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.source_fingerprint"`)}
	}
	if v, ok := _c.mutation.SourceFingerprint(); ok {
		if err := codexregistrationcandidate.SourceFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "source_fingerprint", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_fingerprint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := codexregistrationcandidate.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AccountID(); ok {
		if err := codexregistrationcandidate.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.account_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := codexregistrationcandidate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LivenessStatus(); !ok {
		return &ValidationError{Name: "liveness_status", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.liveness_status"`)}
	}
	if v, ok := _c.mutation.LivenessStatus(); ok {
		if err := codexregistrationcandidate.LivenessStatusValidator(v); err != nil {
			return &ValidationError{Name: "liveness_status", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.liveness_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WorkflowState(); !ok {
		return &ValidationError{Name: "workflow_state", err: errors.New(`ent: missing required field "CodexRegistrationCandidate.workflow_state"`)}
	}
	if v, ok := _c.mutation.WorkflowState(); ok {
		if err := codexregistrationcandidate.WorkflowStateValidator(v); err != nil {
			return &ValidationError{Name: "workflow_state", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.workflow_state": %w`, err)}
		}
	}
	return nil
}

func (_c *CodexRegistrationCandidateCreate) sqlSave(ctx context.Context) (*CodexRegistrationCandidate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexRegistrationCandidateCreate) createSpec() (*CodexRegistrationCandidate, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexRegistrationCandidate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexregistrationcandidate.Table, sqlgraph.NewFieldSpec(codexregistrationcandidate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SourcePath(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourcePath, field.TypeString, value)
		_node.SourcePath = value
	}
	if value, ok := _c.mutation.SourceFilename(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceFilename, field.TypeString, value)
		_node.SourceFilename = value
	}
	if value, ok := _c.mutation.SourceMtime(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceMtime, field.TypeTime, value)
		_node.SourceMtime = value
	}
	if value, ok := _c.mutation.SourceFingerprint(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceFingerprint, field.TypeString, value)
		_node.SourceFingerprint = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(codexregistrationcandidate.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(codexregistrationcandidate.FieldAccountID, field.TypeString, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(codexregistrationcandidate.FieldType, field.TypeString, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastRefreshAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLastRefreshAt, field.TypeTime, value)
		_node.LastRefreshAt = &value
	}
	if value, ok := _c.mutation.LivenessStatus(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLivenessStatus, field.TypeString, value)
		_node.LivenessStatus = value
	}
	if value, ok := _c.mutation.WorkflowState(); ok {
		_spec.SetField(codexregistrationcandidate.FieldWorkflowState, field.TypeString, value)
		_node.WorkflowState = value
	}
	if value, ok := _c.mutation.StatusReason(); ok {
		_spec.SetField(codexregistrationcandidate.FieldStatusReason, field.TypeString, value)
		_node.StatusReason = &value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.ImportedAccountID(); ok {
		_spec.SetField(codexregistrationcandidate.FieldImportedAccountID, field.TypeInt64, value)
		_node.ImportedAccountID = &value
	}
	if value, ok := _c.mutation.ImportedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldImportedAt, field.TypeTime, value)
		_node.ImportedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexRegistrationCandidate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexRegistrationCandidateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexRegistrationCandidateCreate) OnConflict(opts ...sql.ConflictOption) *CodexRegistrationCandidateUpsertOne {
	_c.conflict = opts
	return &CodexRegistrationCandidateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexRegistrationCandidate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexRegistrationCandidateCreate) OnConflictColumns(columns ...string) *CodexRegistrationCandidateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexRegistrationCandidateUpsertOne{
		create: _c,
	}
}

type (
	// CodexRegistrationCandidateUpsertOne is the builder for "upsert"-ing
	//  one CodexRegistrationCandidate node.
	CodexRegistrationCandidateUpsertOne struct {
		create *CodexRegistrationCandidateCreate
	}

	// CodexRegistrationCandidateUpsert is the "OnConflict" setter.
	CodexRegistrationCandidateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexRegistrationCandidateUpsert) SetUpdatedAt(v time.Time) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateUpdatedAt() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldUpdatedAt)
	return u
}

// SetSourcePath sets the "source_path" field.
func (u *CodexRegistrationCandidateUpsert) SetSourcePath(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldSourcePath, v)
	return u
}

// UpdateSourcePath sets the "source_path" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateSourcePath() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldSourcePath)
	return u
}

// SetSourceFilename sets the "source_filename" field.
func (u *CodexRegistrationCandidateUpsert) SetSourceFilename(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldSourceFilename, v)
	return u
}

// UpdateSourceFilename sets the "source_filename" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateSourceFilename() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldSourceFilename)
	return u
}

// SetSourceMtime sets the "source_mtime" field.
func (u *CodexRegistrationCandidateUpsert) SetSourceMtime(v time.Time) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldSourceMtime, v)
	return u
}

// UpdateSourceMtime sets the "source_mtime" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateSourceMtime() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldSourceMtime)
	return u
}

// SetSourceFingerprint sets the "source_fingerprint" field.
func (u *CodexRegistrationCandidateUpsert) SetSourceFingerprint(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldSourceFingerprint, v)
	return u
}

// UpdateSourceFingerprint sets the "source_fingerprint" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateSourceFingerprint() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldSourceFingerprint)
	return u
}

// SetEmail sets the "email" field.
func (u *CodexRegistrationCandidateUpsert) SetEmail(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateEmail() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *CodexRegistrationCandidateUpsert) ClearEmail() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldEmail)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *CodexRegistrationCandidateUpsert) SetAccountID(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateAccountID() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldAccountID)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *CodexRegistrationCandidateUpsert) ClearAccountID() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldAccountID)
	return u
}

// SetType sets the "type" field.
func (u *CodexRegistrationCandidateUpsert) SetType(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateType() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldType)
	return u
}

// ClearType clears the value of the "type" field.
func (u *CodexRegistrationCandidateUpsert) ClearType() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldType)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexRegistrationCandidateUpsert) SetExpiresAt(v time.Time) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateExpiresAt() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CodexRegistrationCandidateUpsert) ClearExpiresAt() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldExpiresAt)
	return u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *CodexRegistrationCandidateUpsert) SetLastRefreshAt(v time.Time) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldLastRefreshAt, v)
	return u
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateLastRefreshAt() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldLastRefreshAt)
	return u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *CodexRegistrationCandidateUpsert) ClearLastRefreshAt() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldLastRefreshAt)
	return u
}

// SetLivenessStatus sets the "liveness_status" field.
func (u *CodexRegistrationCandidateUpsert) SetLivenessStatus(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldLivenessStatus, v)
	return u
}

// UpdateLivenessStatus sets the "liveness_status" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateLivenessStatus() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldLivenessStatus)
	return u
}

// SetWorkflowState sets the "workflow_state" field.
func (u *CodexRegistrationCandidateUpsert) SetWorkflowState(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldWorkflowState, v)
	return u
}

// UpdateWorkflowState sets the "workflow_state" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateWorkflowState() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldWorkflowState)
	return u
}

// SetStatusReason sets the "status_reason" field.
func (u *CodexRegistrationCandidateUpsert) SetStatusReason(v string) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldStatusReason, v)
	return u
}

// UpdateStatusReason sets the "status_reason" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateStatusReason() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldStatusReason)
	return u
}

// ClearStatusReason clears the value of the "status_reason" field.
func (u *CodexRegistrationCandidateUpsert) ClearStatusReason() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldStatusReason)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *CodexRegistrationCandidateUpsert) SetLastCheckedAt(v time.Time) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateLastCheckedAt() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *CodexRegistrationCandidateUpsert) ClearLastCheckedAt() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldLastCheckedAt)
	return u
}

// SetImportedAccountID sets the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsert) SetImportedAccountID(v int64) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldImportedAccountID, v)
	return u
}

// UpdateImportedAccountID sets the "imported_account_id" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateImportedAccountID() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldImportedAccountID)
	return u
}

// AddImportedAccountID adds v to the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsert) AddImportedAccountID(v int64) *CodexRegistrationCandidateUpsert {
	u.Add(codexregistrationcandidate.FieldImportedAccountID, v)
	return u
}

// ClearImportedAccountID clears the value of the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsert) ClearImportedAccountID() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldImportedAccountID)
	return u
}

// SetImportedAt sets the "imported_at" field.
func (u *CodexRegistrationCandidateUpsert) SetImportedAt(v time.Time) *CodexRegistrationCandidateUpsert {
	u.Set(codexregistrationcandidate.FieldImportedAt, v)
	return u
}

// UpdateImportedAt sets the "imported_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsert) UpdateImportedAt() *CodexRegistrationCandidateUpsert {
	u.SetExcluded(codexregistrationcandidate.FieldImportedAt)
	return u
}

// ClearImportedAt clears the value of the "imported_at" field.
func (u *CodexRegistrationCandidateUpsert) ClearImportedAt() *CodexRegistrationCandidateUpsert {
	u.SetNull(codexregistrationcandidate.FieldImportedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CodexRegistrationCandidate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexRegistrationCandidateUpsertOne) UpdateNewValues() *CodexRegistrationCandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(codexregistrationcandidate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexRegistrationCandidate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodexRegistrationCandidateUpsertOne) Ignore() *CodexRegistrationCandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexRegistrationCandidateUpsertOne) DoNothing() *CodexRegistrationCandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexRegistrationCandidateCreate.OnConflict
// documentation for more info.
func (u *CodexRegistrationCandidateUpsertOne) Update(set func(*CodexRegistrationCandidateUpsert)) *CodexRegistrationCandidateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexRegistrationCandidateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexRegistrationCandidateUpsertOne) SetUpdatedAt(v time.Time) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateUpdatedAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSourcePath sets the "source_path" field.
func (u *CodexRegistrationCandidateUpsertOne) SetSourcePath(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourcePath(v)
	})
}

// UpdateSourcePath sets the "source_path" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateSourcePath() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourcePath()
	})
}

// SetSourceFilename sets the "source_filename" field.
func (u *CodexRegistrationCandidateUpsertOne) SetSourceFilename(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourceFilename(v)
	})
}

// UpdateSourceFilename sets the "source_filename" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateSourceFilename() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourceFilename()
	})
}

// SetSourceMtime sets the "source_mtime" field.
func (u *CodexRegistrationCandidateUpsertOne) SetSourceMtime(v time.Time) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourceMtime(v)
	})
}

// UpdateSourceMtime sets the "source_mtime" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateSourceMtime() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourceMtime()
	})
}

// SetSourceFingerprint sets the "source_fingerprint" field.
func (u *CodexRegistrationCandidateUpsertOne) SetSourceFingerprint(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourceFingerprint(v)
	})
}

// UpdateSourceFingerprint sets the "source_fingerprint" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateSourceFingerprint() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourceFingerprint()
	})
}

// SetEmail sets the "email" field.
func (u *CodexRegistrationCandidateUpsertOne) SetEmail(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateEmail() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearEmail() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearEmail()
	})
}

// SetAccountID sets the "account_id" field.
func (u *CodexRegistrationCandidateUpsertOne) SetAccountID(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateAccountID() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearAccountID() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearAccountID()
	})
}

// SetType sets the "type" field.
func (u *CodexRegistrationCandidateUpsertOne) SetType(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateType() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearType() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearType()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexRegistrationCandidateUpsertOne) SetExpiresAt(v time.Time) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateExpiresAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearExpiresAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *CodexRegistrationCandidateUpsertOne) SetLastRefreshAt(v time.Time) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetLastRefreshAt(v)
	})
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateLastRefreshAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateLastRefreshAt()
	})
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearLastRefreshAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearLastRefreshAt()
	})
}

// SetLivenessStatus sets the "liveness_status" field.
func (u *CodexRegistrationCandidateUpsertOne) SetLivenessStatus(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetLivenessStatus(v)
	})
}

// UpdateLivenessStatus sets the "liveness_status" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateLivenessStatus() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateLivenessStatus()
	})
}

// SetWorkflowState sets the "workflow_state" field.
func (u *CodexRegistrationCandidateUpsertOne) SetWorkflowState(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetWorkflowState(v)
	})
}

// UpdateWorkflowState sets the "workflow_state" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateWorkflowState() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateWorkflowState()
	})
}

// SetStatusReason sets the "status_reason" field.
func (u *CodexRegistrationCandidateUpsertOne) SetStatusReason(v string) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetStatusReason(v)
	})
}

// UpdateStatusReason sets the "status_reason" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateStatusReason() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateStatusReason()
	})
}

// ClearStatusReason clears the value of the "status_reason" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearStatusReason() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearStatusReason()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *CodexRegistrationCandidateUpsertOne) SetLastCheckedAt(v time.Time) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateLastCheckedAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearLastCheckedAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetImportedAccountID sets the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsertOne) SetImportedAccountID(v int64) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetImportedAccountID(v)
	})
}

// AddImportedAccountID adds v to the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsertOne) AddImportedAccountID(v int64) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.AddImportedAccountID(v)
	})
}

// UpdateImportedAccountID sets the "imported_account_id" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateImportedAccountID() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateImportedAccountID()
	})
}

// ClearImportedAccountID clears the value of the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearImportedAccountID() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearImportedAccountID()
	})
}

// SetImportedAt sets the "imported_at" field.
func (u *CodexRegistrationCandidateUpsertOne) SetImportedAt(v time.Time) *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetImportedAt(v)
	})
}

// UpdateImportedAt sets the "imported_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertOne) UpdateImportedAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateImportedAt()
	})
}

// ClearImportedAt clears the value of the "imported_at" field.
func (u *CodexRegistrationCandidateUpsertOne) ClearImportedAt() *CodexRegistrationCandidateUpsertOne {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearImportedAt()
	})
}

// Exec executes the query.
func (u *CodexRegistrationCandidateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexRegistrationCandidateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexRegistrationCandidateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodexRegistrationCandidateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodexRegistrationCandidateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodexRegistrationCandidateCreateBulk is the builder for creating many CodexRegistrationCandidate entities in bulk.
type CodexRegistrationCandidateCreateBulk struct {
	config
	err      error
	builders []*CodexRegistrationCandidateCreate
	conflict []sql.ConflictOption
}

// Save creates the CodexRegistrationCandidate entities in the database.
func (_c *CodexRegistrationCandidateCreateBulk) Save(ctx context.Context) ([]*CodexRegistrationCandidate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexRegistrationCandidate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexRegistrationCandidateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexRegistrationCandidateCreateBulk) SaveX(ctx context.Context) []*CodexRegistrationCandidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexRegistrationCandidateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexRegistrationCandidateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodexRegistrationCandidate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodexRegistrationCandidateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CodexRegistrationCandidateCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodexRegistrationCandidateUpsertBulk {
	_c.conflict = opts
	return &CodexRegistrationCandidateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodexRegistrationCandidate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodexRegistrationCandidateCreateBulk) OnConflictColumns(columns ...string) *CodexRegistrationCandidateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodexRegistrationCandidateUpsertBulk{
		create: _c,
	}
}

// CodexRegistrationCandidateUpsertBulk is the builder for "upsert"-ing
// a bulk of CodexRegistrationCandidate nodes.
type CodexRegistrationCandidateUpsertBulk struct {
	create *CodexRegistrationCandidateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodexRegistrationCandidate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CodexRegistrationCandidateUpsertBulk) UpdateNewValues() *CodexRegistrationCandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(codexregistrationcandidate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodexRegistrationCandidate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodexRegistrationCandidateUpsertBulk) Ignore() *CodexRegistrationCandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodexRegistrationCandidateUpsertBulk) DoNothing() *CodexRegistrationCandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodexRegistrationCandidateCreateBulk.OnConflict
// documentation for more info.
func (u *CodexRegistrationCandidateUpsertBulk) Update(set func(*CodexRegistrationCandidateUpsert)) *CodexRegistrationCandidateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodexRegistrationCandidateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetUpdatedAt(v time.Time) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateUpdatedAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSourcePath sets the "source_path" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetSourcePath(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourcePath(v)
	})
}

// UpdateSourcePath sets the "source_path" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateSourcePath() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourcePath()
	})
}

// SetSourceFilename sets the "source_filename" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetSourceFilename(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourceFilename(v)
	})
}

// UpdateSourceFilename sets the "source_filename" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateSourceFilename() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourceFilename()
	})
}

// SetSourceMtime sets the "source_mtime" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetSourceMtime(v time.Time) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourceMtime(v)
	})
}

// UpdateSourceMtime sets the "source_mtime" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateSourceMtime() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourceMtime()
	})
}

// SetSourceFingerprint sets the "source_fingerprint" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetSourceFingerprint(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetSourceFingerprint(v)
	})
}

// UpdateSourceFingerprint sets the "source_fingerprint" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateSourceFingerprint() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateSourceFingerprint()
	})
}

// SetEmail sets the "email" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetEmail(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateEmail() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearEmail() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearEmail()
	})
}

// SetAccountID sets the "account_id" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetAccountID(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateAccountID() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearAccountID() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearAccountID()
	})
}

// SetType sets the "type" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetType(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateType() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearType() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearType()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetExpiresAt(v time.Time) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateExpiresAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearExpiresAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetLastRefreshAt(v time.Time) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetLastRefreshAt(v)
	})
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateLastRefreshAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateLastRefreshAt()
	})
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearLastRefreshAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearLastRefreshAt()
	})
}

// SetLivenessStatus sets the "liveness_status" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetLivenessStatus(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetLivenessStatus(v)
	})
}

// UpdateLivenessStatus sets the "liveness_status" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateLivenessStatus() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateLivenessStatus()
	})
}

// SetWorkflowState sets the "workflow_state" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetWorkflowState(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetWorkflowState(v)
	})
}

// UpdateWorkflowState sets the "workflow_state" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateWorkflowState() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateWorkflowState()
	})
}

// SetStatusReason sets the "status_reason" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetStatusReason(v string) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetStatusReason(v)
	})
}

// UpdateStatusReason sets the "status_reason" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateStatusReason() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateStatusReason()
	})
}

// ClearStatusReason clears the value of the "status_reason" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearStatusReason() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearStatusReason()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetLastCheckedAt(v time.Time) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateLastCheckedAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearLastCheckedAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetImportedAccountID sets the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetImportedAccountID(v int64) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetImportedAccountID(v)
	})
}

// AddImportedAccountID adds v to the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsertBulk) AddImportedAccountID(v int64) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.AddImportedAccountID(v)
	})
}

// UpdateImportedAccountID sets the "imported_account_id" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateImportedAccountID() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateImportedAccountID()
	})
}

// ClearImportedAccountID clears the value of the "imported_account_id" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearImportedAccountID() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearImportedAccountID()
	})
}

// SetImportedAt sets the "imported_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) SetImportedAt(v time.Time) *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.SetImportedAt(v)
	})
}

// UpdateImportedAt sets the "imported_at" field to the value that was provided on create.
func (u *CodexRegistrationCandidateUpsertBulk) UpdateImportedAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.UpdateImportedAt()
	})
}

// ClearImportedAt clears the value of the "imported_at" field.
func (u *CodexRegistrationCandidateUpsertBulk) ClearImportedAt() *CodexRegistrationCandidateUpsertBulk {
	return u.Update(func(s *CodexRegistrationCandidateUpsert) {
		s.ClearImportedAt()
	})
}

// Exec executes the query.
func (u *CodexRegistrationCandidateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodexRegistrationCandidateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodexRegistrationCandidateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodexRegistrationCandidateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
