// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexregistrationcandidate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CodexRegistrationCandidateUpdate is the builder for updating CodexRegistrationCandidate entities.
type CodexRegistrationCandidateUpdate struct {
	config
	hooks    []Hook
	mutation *CodexRegistrationCandidateMutation
}

// Where appends a list predicates to the CodexRegistrationCandidateUpdate builder.
func (_u *CodexRegistrationCandidateUpdate) Where(ps ...predicate.CodexRegistrationCandidate) *CodexRegistrationCandidateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexRegistrationCandidateUpdate) SetUpdatedAt(v time.Time) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *CodexRegistrationCandidateUpdate) SetSourcePath(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableSourcePath(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetSourceFilename sets the "source_filename" field.
func (_u *CodexRegistrationCandidateUpdate) SetSourceFilename(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetSourceFilename(v)
	return _u
}

// SetNillableSourceFilename sets the "source_filename" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableSourceFilename(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetSourceFilename(*v)
	}
	return _u
}

// SetSourceMtime sets the "source_mtime" field.
func (_u *CodexRegistrationCandidateUpdate) SetSourceMtime(v time.Time) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetSourceMtime(v)
	return _u
}

// SetNillableSourceMtime sets the "source_mtime" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableSourceMtime(v *time.Time) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetSourceMtime(*v)
	}
	return _u
}

// SetSourceFingerprint sets the "source_fingerprint" field.
func (_u *CodexRegistrationCandidateUpdate) SetSourceFingerprint(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetSourceFingerprint(v)
	return _u
}

// SetNillableSourceFingerprint sets the "source_fingerprint" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableSourceFingerprint(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetSourceFingerprint(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CodexRegistrationCandidateUpdate) SetEmail(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableEmail(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *CodexRegistrationCandidateUpdate) ClearEmail() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CodexRegistrationCandidateUpdate) SetAccountID(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableAccountID(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *CodexRegistrationCandidateUpdate) ClearAccountID() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetType sets the "type" field.
func (_u *CodexRegistrationCandidateUpdate) SetType(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableType(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *CodexRegistrationCandidateUpdate) ClearType() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearType()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexRegistrationCandidateUpdate) SetExpiresAt(v time.Time) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableExpiresAt(v *time.Time) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CodexRegistrationCandidateUpdate) ClearExpiresAt() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_u *CodexRegistrationCandidateUpdate) SetLastRefreshAt(v time.Time) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetLastRefreshAt(v)
	return _u
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableLastRefreshAt(v *time.Time) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetLastRefreshAt(*v)
	}
	return _u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (_u *CodexRegistrationCandidateUpdate) ClearLastRefreshAt() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearLastRefreshAt()
	return _u
}

// SetLivenessStatus sets the "liveness_status" field.
func (_u *CodexRegistrationCandidateUpdate) SetLivenessStatus(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetLivenessStatus(v)
	return _u
}

// SetNillableLivenessStatus sets the "liveness_status" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableLivenessStatus(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetLivenessStatus(*v)
	}
	return _u
}

// SetWorkflowState sets the "workflow_state" field.
func (_u *CodexRegistrationCandidateUpdate) SetWorkflowState(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetWorkflowState(v)
	return _u
}

// SetNillableWorkflowState sets the "workflow_state" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableWorkflowState(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetWorkflowState(*v)
	}
	return _u
}

// SetStatusReason sets the "status_reason" field.
func (_u *CodexRegistrationCandidateUpdate) SetStatusReason(v string) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetStatusReason(v)
	return _u
}

// SetNillableStatusReason sets the "status_reason" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableStatusReason(v *string) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetStatusReason(*v)
	}
	return _u
}

// ClearStatusReason clears the value of the "status_reason" field.
func (_u *CodexRegistrationCandidateUpdate) ClearStatusReason() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearStatusReason()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *CodexRegistrationCandidateUpdate) SetLastCheckedAt(v time.Time) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableLastCheckedAt(v *time.Time) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *CodexRegistrationCandidateUpdate) ClearLastCheckedAt() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetImportedAccountID sets the "imported_account_id" field.
func (_u *CodexRegistrationCandidateUpdate) SetImportedAccountID(v int64) *CodexRegistrationCandidateUpdate {
	_u.mutation.ResetImportedAccountID()
	_u.mutation.SetImportedAccountID(v)
	return _u
}

// SetNillableImportedAccountID sets the "imported_account_id" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableImportedAccountID(v *int64) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetImportedAccountID(*v)
	}
	return _u
}

// AddImportedAccountID adds value to the "imported_account_id" field.
func (_u *CodexRegistrationCandidateUpdate) AddImportedAccountID(v int64) *CodexRegistrationCandidateUpdate {
	_u.mutation.AddImportedAccountID(v)
	return _u
}

// ClearImportedAccountID clears the value of the "imported_account_id" field.
func (_u *CodexRegistrationCandidateUpdate) ClearImportedAccountID() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearImportedAccountID()
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *CodexRegistrationCandidateUpdate) SetImportedAt(v time.Time) *CodexRegistrationCandidateUpdate {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdate) SetNillableImportedAt(v *time.Time) *CodexRegistrationCandidateUpdate {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// ClearImportedAt clears the value of the "imported_at" field.
func (_u *CodexRegistrationCandidateUpdate) ClearImportedAt() *CodexRegistrationCandidateUpdate {
	_u.mutation.ClearImportedAt()
	return _u
}

// Mutation returns the CodexRegistrationCandidateMutation object of the builder.
func (_u *CodexRegistrationCandidateUpdate) Mutation() *CodexRegistrationCandidateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexRegistrationCandidateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexRegistrationCandidateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexRegistrationCandidateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexRegistrationCandidateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexRegistrationCandidateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexregistrationcandidate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexRegistrationCandidateUpdate) check() error {
	if v, ok := _u.mutation.SourcePath(); ok {
		if err := codexregistrationcandidate.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFilename(); ok {
		if err := codexregistrationcandidate.SourceFilenameValidator(v); err != nil {
			return &ValidationError{Name: "source_filename", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFingerprint(); ok {
		if err := codexregistrationcandidate.SourceFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "source_fingerprint", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := codexregistrationcandidate.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := codexregistrationcandidate.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := codexregistrationcandidate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LivenessStatus(); ok {
		if err := codexregistrationcandidate.LivenessStatusValidator(v); err != nil {
			return &ValidationError{Name: "liveness_status", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.liveness_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkflowState(); ok {
		if err := codexregistrationcandidate.WorkflowStateValidator(v); err != nil {
			return &ValidationError{Name: "workflow_state", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.workflow_state": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexRegistrationCandidateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexregistrationcandidate.Table, codexregistrationcandidate.Columns, sqlgraph.NewFieldSpec(codexregistrationcandidate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFilename(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceMtime(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceMtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceFingerprint(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(codexregistrationcandidate.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(codexregistrationcandidate.FieldAccountID, field.TypeString, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(codexregistrationcandidate.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRefreshAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLastRefreshAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldLastRefreshAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LivenessStatus(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLivenessStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowState(); ok {
		_spec.SetField(codexregistrationcandidate.FieldWorkflowState, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusReason(); ok {
		_spec.SetField(codexregistrationcandidate.FieldStatusReason, field.TypeString, value)
	}
	if _u.mutation.StatusReasonCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldStatusReason, field.TypeString)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ImportedAccountID(); ok {
		_spec.SetField(codexregistrationcandidate.FieldImportedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImportedAccountID(); ok {
		_spec.AddField(codexregistrationcandidate.FieldImportedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.ImportedAccountIDCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldImportedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldImportedAt, field.TypeTime, value)
	}
	if _u.mutation.ImportedAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldImportedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexregistrationcandidate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexRegistrationCandidateUpdateOne is the builder for updating a single CodexRegistrationCandidate entity.
type CodexRegistrationCandidateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexRegistrationCandidateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetUpdatedAt(v time.Time) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetSourcePath(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableSourcePath(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetSourceFilename sets the "source_filename" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetSourceFilename(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetSourceFilename(v)
	return _u
}

// SetNillableSourceFilename sets the "source_filename" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableSourceFilename(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetSourceFilename(*v)
	}
	return _u
}

// SetSourceMtime sets the "source_mtime" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetSourceMtime(v time.Time) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetSourceMtime(v)
	return _u
}

// SetNillableSourceMtime sets the "source_mtime" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableSourceMtime(v *time.Time) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetSourceMtime(*v)
	}
	return _u
}

// SetSourceFingerprint sets the "source_fingerprint" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetSourceFingerprint(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetSourceFingerprint(v)
	return _u
}

// SetNillableSourceFingerprint sets the "source_fingerprint" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableSourceFingerprint(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetSourceFingerprint(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetEmail(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableEmail(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearEmail() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetAccountID(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableAccountID(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearAccountID() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetType sets the "type" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetType(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableType(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearType() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearType()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetExpiresAt(v time.Time) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableExpiresAt(v *time.Time) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearExpiresAt() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetLastRefreshAt(v time.Time) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetLastRefreshAt(v)
	return _u
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableLastRefreshAt(v *time.Time) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetLastRefreshAt(*v)
	}
	return _u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearLastRefreshAt() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearLastRefreshAt()
	return _u
}

// SetLivenessStatus sets the "liveness_status" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetLivenessStatus(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetLivenessStatus(v)
	return _u
}

// SetNillableLivenessStatus sets the "liveness_status" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableLivenessStatus(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetLivenessStatus(*v)
	}
	return _u
}

// SetWorkflowState sets the "workflow_state" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetWorkflowState(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetWorkflowState(v)
	return _u
}

// SetNillableWorkflowState sets the "workflow_state" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableWorkflowState(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetWorkflowState(*v)
	}
	return _u
}

// SetStatusReason sets the "status_reason" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetStatusReason(v string) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetStatusReason(v)
	return _u
}

// SetNillableStatusReason sets the "status_reason" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableStatusReason(v *string) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetStatusReason(*v)
	}
	return _u
}

// ClearStatusReason clears the value of the "status_reason" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearStatusReason() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearStatusReason()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetLastCheckedAt(v time.Time) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableLastCheckedAt(v *time.Time) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearLastCheckedAt() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetImportedAccountID sets the "imported_account_id" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetImportedAccountID(v int64) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ResetImportedAccountID()
	_u.mutation.SetImportedAccountID(v)
	return _u
}

// SetNillableImportedAccountID sets the "imported_account_id" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableImportedAccountID(v *int64) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetImportedAccountID(*v)
	}
	return _u
}

// AddImportedAccountID adds value to the "imported_account_id" field.
func (_u *CodexRegistrationCandidateUpdateOne) AddImportedAccountID(v int64) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.AddImportedAccountID(v)
	return _u
}

// ClearImportedAccountID clears the value of the "imported_account_id" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearImportedAccountID() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearImportedAccountID()
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) SetImportedAt(v time.Time) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *CodexRegistrationCandidateUpdateOne) SetNillableImportedAt(v *time.Time) *CodexRegistrationCandidateUpdateOne {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// ClearImportedAt clears the value of the "imported_at" field.
func (_u *CodexRegistrationCandidateUpdateOne) ClearImportedAt() *CodexRegistrationCandidateUpdateOne {
	_u.mutation.ClearImportedAt()
	return _u
}

// Mutation returns the CodexRegistrationCandidateMutation object of the builder.
func (_u *CodexRegistrationCandidateUpdateOne) Mutation() *CodexRegistrationCandidateMutation {
	return _u.mutation
}

// Where appends a list predicates to the CodexRegistrationCandidateUpdate builder.
func (_u *CodexRegistrationCandidateUpdateOne) Where(ps ...predicate.CodexRegistrationCandidate) *CodexRegistrationCandidateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexRegistrationCandidateUpdateOne) Select(field string, fields ...string) *CodexRegistrationCandidateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexRegistrationCandidate entity.
func (_u *CodexRegistrationCandidateUpdateOne) Save(ctx context.Context) (*CodexRegistrationCandidate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexRegistrationCandidateUpdateOne) SaveX(ctx context.Context) *CodexRegistrationCandidate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexRegistrationCandidateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexRegistrationCandidateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexRegistrationCandidateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexregistrationcandidate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexRegistrationCandidateUpdateOne) check() error {
	if v, ok := _u.mutation.SourcePath(); ok {
		if err := codexregistrationcandidate.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFilename(); ok {
		if err := codexregistrationcandidate.SourceFilenameValidator(v); err != nil {
			return &ValidationError{Name: "source_filename", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFingerprint(); ok {
		if err := codexregistrationcandidate.SourceFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "source_fingerprint", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.source_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := codexregistrationcandidate.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := codexregistrationcandidate.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := codexregistrationcandidate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LivenessStatus(); ok {
		if err := codexregistrationcandidate.LivenessStatusValidator(v); err != nil {
			return &ValidationError{Name: "liveness_status", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.liveness_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkflowState(); ok {
		if err := codexregistrationcandidate.WorkflowStateValidator(v); err != nil {
			return &ValidationError{Name: "workflow_state", err: fmt.Errorf(`ent: validator failed for field "CodexRegistrationCandidate.workflow_state": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexRegistrationCandidateUpdateOne) sqlSave(ctx context.Context) (_node *CodexRegistrationCandidate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexregistrationcandidate.Table, codexregistrationcandidate.Columns, sqlgraph.NewFieldSpec(codexregistrationcandidate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexRegistrationCandidate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexregistrationcandidate.FieldID)
		for _, f := range fields {
			if !codexregistrationcandidate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexregistrationcandidate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFilename(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceMtime(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceMtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceFingerprint(); ok {
		_spec.SetField(codexregistrationcandidate.FieldSourceFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(codexregistrationcandidate.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(codexregistrationcandidate.FieldAccountID, field.TypeString, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(codexregistrationcandidate.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRefreshAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLastRefreshAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldLastRefreshAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LivenessStatus(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLivenessStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowState(); ok {
		_spec.SetField(codexregistrationcandidate.FieldWorkflowState, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusReason(); ok {
		_spec.SetField(codexregistrationcandidate.FieldStatusReason, field.TypeString, value)
	}
	if _u.mutation.StatusReasonCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldStatusReason, field.TypeString)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ImportedAccountID(); ok {
		_spec.SetField(codexregistrationcandidate.FieldImportedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImportedAccountID(); ok {
		_spec.AddField(codexregistrationcandidate.FieldImportedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.ImportedAccountIDCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldImportedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(codexregistrationcandidate.FieldImportedAt, field.TypeTime, value)
	}
	if _u.mutation.ImportedAtCleared() {
		_spec.ClearField(codexregistrationcandidate.FieldImportedAt, field.TypeTime)
	}
	_node = &CodexRegistrationCandidate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexregistrationcandidate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
