// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/codexregistrationcandidate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CodexRegistrationCandidateDelete is the builder for deleting a CodexRegistrationCandidate entity.
type CodexRegistrationCandidateDelete struct {
	config
	hooks    []Hook
	mutation *CodexRegistrationCandidateMutation
}

// Where appends a list predicates to the CodexRegistrationCandidateDelete builder.
func (_d *CodexRegistrationCandidateDelete) Where(ps ...predicate.CodexRegistrationCandidate) *CodexRegistrationCandidateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CodexRegistrationCandidateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexRegistrationCandidateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CodexRegistrationCandidateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(codexregistrationcandidate.Table, sqlgraph.NewFieldSpec(codexregistrationcandidate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CodexRegistrationCandidateDeleteOne is the builder for deleting a single CodexRegistrationCandidate entity.
type CodexRegistrationCandidateDeleteOne struct {
	_d *CodexRegistrationCandidateDelete
}

// Where appends a list predicates to the CodexRegistrationCandidateDelete builder.
func (_d *CodexRegistrationCandidateDeleteOne) Where(ps ...predicate.CodexRegistrationCandidate) *CodexRegistrationCandidateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CodexRegistrationCandidateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{codexregistrationcandidate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexRegistrationCandidateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
